#pragma once

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 750
#define LEADER_NO_TIMEOUT

// #define AUTO_SHIFT_TIMEOUT 140
// #define AUTO_SHIFT_TIMEOUT_PER_KEY
// #define NO_AUTO_SHIFT_NUMERIC

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 7
#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY
#define TAPPING_FORCE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_ONLY_FROM_LAYER 0

#define SPLIT_LAYER_STATE_ENABLE
