#pragma once

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define LEADER_NO_TIMEOUT

// #define AUTO_SHIFT_TIMEOUT 140
// #define AUTO_SHIFT_TIMEOUT_PER_KEY
// #define NO_AUTO_SHIFT_NUMERIC

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 9
#define MOUSEKEY_TIME_TO_MAX 25
#define MOUSEKEY_MOVE_DELTA 4
// #define MK_KINETIC_SPEED

#define TAPPING_TERM 250
#define QUICK_TAP_TERM 120
// #define TAPPING_TERM_PER_KEY
// #define TAPPING_FORCE_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS
// #define PERMISSIVE_HOLD

// Auto Shift
#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT 150
#define AUTO_SHIFT_NO_SETUP

#define CAPS_WORD_IDLE_TIMEOUT 0
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// #define SPLIT_LAYER_STATE_ENABLE
#define ENABLE_COMPILE_KEYCODE

#define FORCE_NKRO
#define COMBO_SHOULD_TRIGGER
