MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
LEADER_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = no
# TAP_DANCE_ENABLE = yes
# OLED_SUGAR = no
REPEAT_KEY_ENABLE = no
CAPS_WORD_ENABLE = yes
VPATH += keyboards/gboards

EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
STENO_ENABLE = yes
STENO_PROTOCOL = txbolt
